.\" Manpage for ctanbib.
.\" Contact michal.h21@gmail.com to correct errors or typos.
.TH ctanbib 1 "18 Sep 2023" "0.2c" "ctanbib man page"
.SH NAME
ctanbib
\- retrieve bibliographic information for packages hosted on CTAN.
.SH SYNOPSIS
ctanbib <options> [package name]
.SH DESCRIPTION
This command can retrieve bibliographic information for TeX packages hosted on
CTAN in the BibTeX format.
.SH OPTIONS
.IP -c,--ctan 
use @ctan type instead of @manual. The difference between the two is that the
url field contains package CTAN path, instead of link to the package.
.IP -C,--CTAN 
like --ctan option, but use original url instead of CTAN path.
.IP -h,--help 
print the help message.
.IP -p,--pkgname
put the package name in a \ctanbibpkgname command. This command can be
redefined in the document for the desired formatting.
.IP -v,--version 
print the version info.
.SH EXAMPLES

$ ctanbib latex  

.Pp 
This invocation will print data in the BibLaTeX format to the standard output:

.nf
.ft CW
@manual{latex,
  title = {The Latex package},
  subtitle = {A TeX macro package that defines LaTeX},
  author = {Lamport, Leslie and The LaTeX Team},
  url = {http://www.latex-project.org/},
  urldate = {2018-08-23}, 
  date = {2018-04-01},
  version = {PL 5}
}
.ft R
.fi

.Pp
The --ctan option:

$ ctanbib -c hyperref

.Pp
This produces bib record with the @ctan type:

.nf
.ft CW
@ctan{hyperref,
title = {The Hyperref package},
subtitle = {Extensive support for hypertext in LaTeX},
author = {Rahtz, Sebastian and Oberdiek, Heiko},
url = {/macros/latex/contrib/hyperref},
urldate = {2018-08-27}, 
date = {},
version = {6.86b}
}
.ft R
.fi

.SH See also
See ctanbib-doc.pdf for more details
.SH BUGS
No known bugs.
.SH AUTHOR
Michal Hoftich (michal.h21@gmail.com)
.SH LICENSE
Permission is granted to copy, distribute and/or modify this software
under the terms of the LaTeX Project Public License, version 1.3.

